### ISSUE TITLE
Enhance copybooks support

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-lsp-for-cobol#71] opened 2019-11-07 15:08 UTC
## Description:
Enhance and improve the copybooks support - TBD

## Acceptance criteria
- Built the text of the copybook inside the program text to analyze it as a one complete program

**Comment by temanbrcom** [comment] 2019-11-22 14:25
Duplicate of #25

**Closed by temanbrcom** 2019-11-22 14:25 UTC
Labels: enhancement
