### ISSUE TITLE
Specified CPY paths are not followed

### ISSUE THREAD

**Issue by MocniMax** [eclipse/che-che4z-lsp-for-cobol#956] opened 2021-06-16 12:32 UTC
Hello again.

When I specify more than one local and/or global paths for copybook include in cobol-lsp.cpy-manager.paths-local setting, only first local and first full paths are searched, others are not.
Even in active paths, not all copybooks are recognized, only few of them.

Here is my cobol-lsp.cpy-manager.paths-local:
"cobol-lsp.cpy-manager.paths-local": [
            "DIR1\\CPY\\COBOL",
            "DIR2\\DIR3\\CPY\\COBOL",
            "C:\\DIR4\\DIR5\\CPY\\COBOL"
        ]
   
Am I doing something wrong? Any idea?

Thanks.

**Comment by temanbrcom** [comment] 2021-06-16 14:18
Hi @MocniMax,

Could you, please, give me examples of copybooks that are not recognized? Is there anything specific in their names?
Thank you.

**Comment by MocniMax** [comment] 2021-06-17 06:58
Hi @**temanbrcom** ,

Now all of my copybooks are recognized as "COBOL Copybook" but still not all are resolved within COBOL program.

There is nothing special with their names and /or content. All our modules follow zOS naming syntax so their names are eight Alpha numeric characters long.

Interesting thing is that issue starts when COBOL module copybooks are stored in more than one directory (i.e. some are global and some are only particular module or project related). In that case, few copybooks from the same location are properly resolved while others are not.

Can I collect somehow some debug info that can help?

Regards

**Comment by temanbrcom** [comment] 2021-06-17 10:39
Hi @MocniMax,

It's interesting. I noticed that you have one slash in the path, and I have two. Please, check if specifying the settings as this helps:
```
    "cobol-lsp.cpy-manager.paths-local": [
      "DIR2\\DIR3\\CPY\\COBOL",
      "DIR1\\CPY\\COBOL",
      "C:\\DIR4\\DIR5\\CPY\\COBOL"]
```
If not, then let's collect the logs. First, please select "ALL" for the logging level in the plugin setting:
![image](https://user-images.githubusercontent.com/47776865/122380610-58e6c800-cf68-11eb-87b1-335f5ae5fa88.png)

Then, please, try to reproduce the scenario. The logs will be in this file: `C:\Users\<user name>\LSPCobol\logs\app.log`. Please, send it to me.

Thank you.

**Comment by MocniMax** [comment] 2021-06-17 11:33
Hi @**temanbrcom** ,

I wrote it wrongly, it is with double backslash.

Attached is complete log.
[app.log](https://github.com/eclipse/che-che4z-lsp-for-cobol/files/6669803/app.log)

**Comment by temanbrcom** [comment] 2021-06-17 11:56
Thank you, I see an exception here. What encoding do your copybook files have?

**Comment by MocniMax** [comment] 2021-06-17 12:56
All our source modules are encoded in IBM-1252.

**Comment by temanbrcom** [comment] 2021-06-17 13:18
Thank you. Right now we support only UTF-8. I will look for a solution.

**Comment by temanbrcom** [comment] 2021-06-17 13:26
What do you use for downloading the copybooks?

**Comment by MocniMax** [comment] 2021-06-17 13:33
We are using our FTP procedures from AIX which is out second target platform (zOS is the first, major one).
Why should encoding be an issue here? To preserve inter platform compatibility, for any language source modules should be only in ANSI encoding (single byte). Any double byte encoding is problematic, even on single platform.

**Comment by temanbrcom** [comment] 2021-06-17 14:12
Ok, thank you. I will try to reproduce it.

**Comment by temanbrcom** [comment] 2021-06-17 15:01
I hope I found the reason - the problem with Java NIO API. I have prepared a pull request.

**Comment by MocniMax** [comment] 2021-06-18 06:25
Great! 
Can't wait to test it :)).

**Comment by temanbrcom** [comment] 2021-06-18 08:52
Cool! Please, try this one: [build]( https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/fix-copybook-encoding/lastSuccessfulBuild/artifact/cobol-language-support-0.19.0+fix-copybook-encoding.1.vsix)
Here is the instruction on how to install the `vsix` package.
Please, also select `Auto Update Extension - None` in the same menu not to allow VSCode to update the build to the latest stable version from the marketplace. Be careful - with this option all the extensions won't be updated manually, so, please switch it back to "All Extensions" or "Only Enabled Extensions" after the testing.
Thank you!

**Comment by MocniMax** [comment] 2021-06-18 09:26
I just installed it, restarted VS Code and tested it, but issue is still there.

Attached is new log.
[app.log](https://github.com/eclipse/che-che4z-lsp-for-cobol/files/6676048/app.log)

**Comment by temanbrcom** [comment] 2021-06-18 09:48
Could you, please, check that the extension version is as follows?
![image](https://user-images.githubusercontent.com/47776865/122542460-015d6080-d02b-11eb-9e7c-4af5771a5344.png)

**Comment by MocniMax** [comment] 2021-06-18 09:51
Nope, it is still v0.19.0

Let me uninstall it and install it from vsix.

**Comment by MocniMax** [comment] 2021-06-18 10:06
Now it installed proper version and patch is working! 
Thanks a lot.

Will continue to use and test extension :)).

**Comment by temanbrcom** [comment] 2021-06-18 10:10
Cool, I'm glad it works! Thank you!
The fix will present in the next release.

**Closed** 2021-06-23 08:50 UTC
Labels: bug
