### ISSUE TITLE
Copybook is not found but I can click it

### ISSUE THREAD

**Issue by jellypuno** [eclipse/che-che4z-lsp-for-cobol#309] opened 2020-04-22 09:30 UTC
## Description ##
Copybook is not found but it is there.

## Steps to reproduce ##
1. I have my copybooks downloaded manually in my copybooks folder.
2. The error appears stating that it is not found
3. If I click it, it will go to my copybooks
4. If I hover over it, it will show a preview of my copybooks.

## Expected behavior ##
The error will not happen

## Screenshots ##
![Copybook](https://user-images.githubusercontent.com/45042840/79965024-ce055d00-848b-11ea-93c6-14c42a28a523.jpg)

## Environment ##
Windows 10
VS Code

## Additional information ##
Also, I have no idea what this means
![Capture](https://user-images.githubusercontent.com/45042840/79965470-58e65780-848c-11ea-92b4-c606f3f1256a.PNG)

I have set-up my file association for .cpy as _"*.cpy": "COBOL"_

**Comment by sergiuilie** [comment] 2020-04-22 10:32
Hello @jellypuno! Thank you for reaching us! 
Well, that's not actually a bug that you have experienced. Currently, we are focus to work with Zowe Explorer so if you download some copybooks using our LSP you will see that the auto-generated folder is called something like "dataset_path.zowe_connection_name" and we are searching for copybooks under the directories which are formed by the paths you provided in `settings.json` under the Zowe connection also specified in `settings.json`, so, the behavior is expected not to find your manually introduced copybook. The fact that you see the copybook when you click or hover on it, is because of the third-party plugin COBOL, deactivate that extension and you will see that it disappears. 

About file extensions, we are not checking .cpy documents for errors so it is normal to throw an error to inform the user. Even if you assigned your file association that adds no value to LSP4Cobol.
Please take a look at the readme file and let us know if we can help you with something else.

I will close this issue if there are no further comments and I would like to let you know that we are working on improving the user experience regarding the copybooks directory by adding Git experience and not only.

**Comment by jellypuno** [comment] 2020-04-22 10:40
Hi @sergiuilie what if I don't have any Zowe Explorer? If I just want to edit my Cobol Program in VSCode and I don't want to use ZE then why is there an error? Cause I can use Zowe CLI to still upload my program rather than ZE.

**Comment by sergiuilie** [comment] 2020-04-22 10:52
I don't understand your concern here. We are working with ZE for copybooks retrieval. If you want to put manually your copybooks you have to set a fake profile and fake paths in `settings.json`. This is the current behavior, it will be enhanced later on.

**Comment by ishche** [comment] 2020-04-22 11:59
He had a regression with the CopyBook downloader - now we support only copybooks in specific folders where copybook downloader expect to find them. It's `<workspace>/.copybooks/<profilename>/<dataset name>/<copybook name>.cpy`. 
Currently, we are working on the support of local copybook search paths.
Unfortunately, integration with the Bitlang COBOL extension (third-party COBOL plugin) is not at the top of our priorities for now.

**Comment by jellypuno** [comment] 2020-04-22 12:58
Thanks @sergiuilie for helping remove that annoying message through a workaround. If you are going to implement a fix, similar to what you said in the call, then the issue could be closed.

**Comment by zimlu02** [comment] 2020-04-22 16:55
Hi @jellypuno,

We will definitely address the error messages you have mentioned. Also as it was already mentioned we are working on a solution that will recognize copybooks already available in the workspace.

Thank you for your feedback!

**Comment by zacanbrcom** [comment] 2020-04-24 12:57
> Also, I have no idea what this means
> ![Capture](https://user-images.githubusercontent.com/45042840/79965470-58e65780-848c-11ea-92b4-c606f3f1256a.PNG)
> 
> I have set-up my file association for .cpy as _"*.cpy": "COBOL"_

I created an issue here #318.
So far I saw it only in latest version of VSC

**Comment by spgennard** [comment] 2020-08-18 17:16
code4z no longer includes the bitlang.cobol extension, so the behavour of this issue will now have changed.

**Closed** 2020-08-19 07:56 UTC
Labels: bug
