### ISSUE TITLE
PERFORM VARYTING

### ISSUE THREAD

**Issue by zFernand0** [eclipse/che-che4z-lsp-for-cobol#1579] opened 2022-10-14 15:58 UTC
Hello,
The Cobol Snippet "PERFORM VARYING" is labeled PERFORM VARYTING (with a T between the Y and the I).
Could you correct it?
Thanks

on a new line of a cobol program, type "PERFORM VARY"

**Screenshots**
![VSCode-varyting](https://user-images.githubusercontent.com/103997342/195865244-3a5ba726-7df6-4a3c-bffe-bd8a880ac838.png)

OS: Windows
Zowe Explorer Version: v2.3.0

_Originally posted by @ROBIN-Olivier in https://github.com/zowe/vscode-extension-for-zowe/issues/1972_

**Comment by zimlu02** [comment] 2022-10-17 14:46
Hi @zFernand0,

do you know what COBOL LS version has been used? I cannot reproduce it on the latest 1.0.2 version.
Thank you

**Comment by ROBIN-Olivier** [comment] 2022-10-18 06:58
Hi @zimlu02 ,
I don't know what "COBOL LS Version" means.
Do you want my version of the IBM Z Open Editor plugin? it's v2.2.0.

**Comment by zimlu02** [comment] 2022-10-18 09:34
Hi @ROBIN-Olivier,

[COBOL LS](https://marketplace.visualstudio.com/items?itemName=broadcomMFD.cobol-language-support) is language support for COBOL language by Broadcom. 
The error that you see is actually coming from an extension from a different vendor.
You can try our latest COBOL LS version by downloading [this VSIX file](https://ci.eclipse.org/che4z/job/LSP%20for%20COBOL/job/development/lastSuccessfulBuild/artifact/cobol-language-support-1.0.2+development.1239.vsix) and installing in your VSC (simply drag&drop this file into VSC Extension section). Eventually, disable other COBOL support extensions not to get duplicate analysis. 

I will close this issue, but feel free to open a new one for any other topic related to this extension, or contact me directly on: lukas.zima@broadcom.com
Best regards

**Closed by zimlu02** 2022-10-18 09:34 UTC
Labels: bug

**Comment by ROBIN-Olivier** [comment] 2022-10-18 14:57
Hi @zimlu02 
I don't understand the closure.
I'm using the IBM Z OPEN EDITOR plugin and I don't want to change it.
Where should I report an incident concerning this plugin?

**Comment by dboudreaux** [comment] 2022-10-18 15:10
It looks like issues are logged here for the z open editor.
https://github.com/IBM/zopeneditor-about/issues

For context, open editor is an IBM extension that Broadcom does not contribute to. We ( Broadcom) have language support for Cobol what works with Visual Studio code editor.


Dana Boudreau
DevOps & Open Mainframe Engineering | Mainframe Software Division
Broadcom Software
mobile: +420.775.853.523 | ***@***.***
On Oct 18, 2022, 4:57 PM +0200, ROBIN-Olivier ***@***.***>, wrote:
> Hi @zimlu02
> I don't understand the closure.
> I'm using the IBM Z OPEN EDITOR plugin and I don't want to change it.
> Where should I report an incident concerning this plugin?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 
This electronic communication and the information and any files transmitted 
with it, or attached to it, are confidential and are intended solely for 
the use of the individual or entity to whom it is addressed and may contain 
information that is confidential, legally privileged, protected by privacy 
laws, or otherwise restricted from disclosure to anyone else. If you are 
not the intended recipient or the person responsible for delivering the 
e-mail to the intended recipient, you are hereby notified that any use, 
copying, distributing, dissemination, forwarding, printing, or copying of 
this e-mail is strictly prohibited. If you received this e-mail in error, 
please return the e-mail to the sender, delete it from your computer, and 
destroy any printed copy of it.

**Comment by zFernand0** [comment] 2022-10-20 17:37
My apologies, I redirected the issue to the wrong repository.
Moving to the z/OE repo
