### ISSUE TITLE
Concatenate the error message

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-lsp-for-cobol#69] opened 2019-10-18 14:06 UTC
Problem messages contain a string "_generated_diagnostic_collection_name#<guid>" that is longer than the error message itself

**Comment by fox0r** [comment] 2019-11-07 15:45
duplicate of #39 Add source type information in the diagnostic object, to be fixed in v0.9.0

**Closed by fox0r** 2019-11-07 15:45 UTC
