### ISSUE TITLE
Simplify the UX of info message

### ISSUE THREAD

**Issue by zimlu02** [eclipse/che-che4z-lsp-for-cobol#390] opened 2020-06-11 13:22 UTC
**Is your feature request related to a problem?**

As a user I want to see just one info message, that will inform me about the absence some of copybooks and actions she may do in order to resolve them. The message should be generic and short, just to inform Michelle that some of her copybooks are not resolved and navigate her into the settings file to provide data to resolve them.

Acceptance criterias

Only ONE message regarding the missing copybooks can appear at a time!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional information**

**Comment by grianbrcom** [comment] 2020-06-11 14:23
Duplicate of #384

**Closed** 2020-06-18 07:50 UTC
Labels: Rally, new feature
